/*
 * prueba.java
 *
 * Created on 28 de junio de 2008, 8:09
 */
package gui;

import java.awt.Color;
import javax.swing.GroupLayout.ParallelGroup;
import javax.swing.GroupLayout.SequentialGroup;

/**
 *
 * @author  Apocalipsis
 */
public class prueba extends javax.swing.JPanel {

    /** Creates new form prueba */
    public prueba() {
        initComponents();
        this.jPanel1.setBackground(new Color(5,5,5));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDoubleBuffered(false);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButton1)
                        .addGap(37, 37, 37)
                        .addComponent(jButton2)
                        .addGap(32, 32, 32)
                        .addComponent(jButton3)))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)))
        );
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    casilla1 = new gui.Casilla();
    casilla2 = new gui.Casilla();
    casilla3 = new gui.Casilla();
    casilla4 = new gui.Casilla();
    casilla5 = new gui.Casilla();
    casilla6 = new gui.Casilla();
    casilla7 = new gui.Casilla();
    casilla8 = new gui.Casilla();
    casilla9 = new gui.Casilla();
    casilla10 = new gui.Casilla();
    casilla11 = new gui.Casilla();
    casilla12 = new gui.Casilla();
    casilla13 = new gui.Casilla();
    casilla14 = new gui.Casilla();
    jButton1 = new javax.swing.JButton();

    casilla1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    casilla1.setAlignmentY(0.0F);

    casilla2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    casilla2.setAlignmentY(0.0F);

    casilla3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    casilla3.setAlignmentY(0.0F);

    casilla4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    casilla4.setAlignmentY(0.0F);

    casilla5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    casilla5.setAlignmentY(0.0F);

    casilla6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    casilla6.setAlignmentY(0.0F);

    casilla7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    casilla7.setAlignmentY(0.0F);

    casilla8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    casilla8.setAlignmentY(0.0F);

    casilla9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    casilla9.setAlignmentY(0.0F);

    casilla10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    casilla10.setAlignmentY(0.0F);

    casilla11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    casilla11.setAlignmentY(0.0F);

    casilla12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    casilla12.setAlignmentY(0.0F);

    casilla13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    casilla13.setAlignmentY(0.0F);

    casilla14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    casilla14.setAlignmentY(0.0F);
    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);


    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
            //.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            //.addGroup(layout.createSequentialGroup()
            .addComponent(casilla1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(casilla2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(casilla3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)//)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(casilla4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(casilla5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(casilla6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(casilla7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(casilla8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(casilla9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(casilla10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(casilla11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(casilla12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(casilla13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)//)//)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
             
            //.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            //.addGroup(layout.createSequentialGroup()
            
            .addComponent(casilla14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)//)//)
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
            );
    
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(casilla1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(casilla2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(casilla3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(casilla4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(casilla5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(casilla6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(casilla7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(casilla8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(casilla9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(casilla10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(casilla11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(casilla12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(casilla13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(casilla14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(247, Short.MAX_VALUE)));
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    int fil = 10;
    int col = 10;
    int x = 0;
    int y = 0;
    Casilla[][] casillas = new Casilla[fil][col];
    for(x=0; x < col; x++)
    {
        for(y=0; y<fil; y++)
        {
            casillas[x][y]= new Casilla();
            casillas[x][y].setBorder(javax.swing.BorderFactory.createEtchedBorder());
            casillas[x][y].setAlignmentY(0.0F);
            casillas[x][y].setToolTipText(String.valueOf(x)+" "+String.valueOf(y));
            
        }
    }
    
    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    
    
    
    //layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(group));
    
    SequentialGroup grupoS = layout.createSequentialGroup();
    ParallelGroup grupoP =  layout.createParallelGroup();
    
    //SequentialGroup aux1 = layout.createSequentialGroup();
    ParallelGroup aux1 = layout.createParallelGroup();
    SequentialGroup aux2 = layout.createSequentialGroup();
    
    for(y=0; y<fil;y++)
    {
        for(x=0; x<col;x++)
        {
            grupoS.addComponent(casillas[x][y], javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE);
                
            //grupoP.addComponent(casillas[x][y], javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE);
        }
        
            aux2.addGroup(grupoS);
            grupoS = layout.createSequentialGroup();
        
            //aux1.addGroup(grupoP);//.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED);
            //grupoP = layout.createParallelGroup();
    }
    
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aux2));
            
    
    
    for(x=0; x<col;x++)
    {
        for(y=0; y<fil;y++)
        {
            grupoP.addComponent(casillas[x][y], javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE);
        } 
        
            aux1.addGroup(grupoP);//.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED);
            grupoP = layout.createParallelGroup();
    }
    
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aux1));
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
    this.lleva();//GEN-LAST:event_jButton3ActionPerformed
}


public void lleva()
{
    // TODO add your handling code here:
    int fil = 10;
    int col = 10;
    int x = 0;
    int y = 0;
    Casilla[][] casillas = new Casilla[fil][col];
    for(x=0; x < col; x++)
    {
        for(y=0; y<fil; y++)
        {
            casillas[x][y]= new Casilla();
            casillas[x][y].setBorder(javax.swing.BorderFactory.createEtchedBorder());
            casillas[x][y].setToolTipText(String.valueOf(x)+" "+String.valueOf(y));
            
        }
    }
    
    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
   
    ParallelGroup pivoteH = layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING);
    SequentialGroup tempH = layout.createSequentialGroup();
    
    for(y=0; y<fil; y++)
    {
        for(x=0; x < col; x++)
        {
            tempH.addComponent(casillas[x][y], javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE);
        }
        pivoteH.addGroup(tempH);
        tempH = layout.createSequentialGroup();
    }
        
    
    
    SequentialGroup pivoteV = layout.createSequentialGroup();
    ParallelGroup tempV = layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE);
    
    for(y=0; y<fil; y++)
    {
        for(x=0; x < col; x++)
        {
            tempV.addComponent(casillas[x][y], javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE);
        }
        pivoteV.addGroup(tempV);//.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED);
        tempV = layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE);
    }
    
    
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
            .addGroup(layout.createSequentialGroup()
                .addGroup(pivoteH)));
    
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
            .addGroup(pivoteV));
    
}
    private gui.Casilla casilla1;
    private gui.Casilla casilla10;
    private gui.Casilla casilla11;
    private gui.Casilla casilla12;
    private gui.Casilla casilla13;
    private gui.Casilla casilla14;
    private gui.Casilla casilla2;
    private gui.Casilla casilla3;
    private gui.Casilla casilla4;
    private gui.Casilla casilla5;
    private gui.Casilla casilla6;
    private gui.Casilla casilla7;
    private gui.Casilla casilla8;
    private gui.Casilla casilla9;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
